language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - nightly
  - pypy-5.4.1
  - pypy3
install:
  - travis_retry pip install coveralls
  - travis_retry pip install tox-travis
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then travis_retry pip install pyOpenSSL>=16.2.0; fi
script:
  tox
after_success:
  coveralls
